### PR TITLE
upload-tpu-tutorials

### PR DESCRIPTION
**Pull request by CyFeng16**
Hi, 
If accepted, I hope to share my tutorial about how I use the TPU.

C.Feng

### CODE REVIEW

**Review by huan — CHANGES_REQUESTED** [review]
1. Please rename all filenames to lowercase, and replace `#` to `-`. i.e. `_posts/2019-03-03-Chat-about-TPU#2.md` -> `1. Please _posts/2019-03-03-chat-about-tpu-2.md`
1. Please rename all image file name to reflex the blog names. i.e. `edge-xxx.jpg` -> `tpu-edge-xxx.jpg`

**Comment by CyFeng16** [comment]
Filenames had been changed.

**Comment by huan** [comment]
Thank you very much for sharing your knowledge to the community!

**Comment by CyFeng16** [comment]
You are welcome.

**Pull request merged**
